### ISSUE TITLE
How do i build the project

### ISSUE THREAD

**Issue by xGhostRider-Tommy** [e-newton/VectorFieldScreensaver#1]
I know it's old, but maybe u can respond to me, i have intellij but it doesnt let me compile it.
It would be great if u gave me the scr file or just explain to me how to build it.

**Comment by e-newton** [comment]
Hi @xGhostRider-Tommy you can find the source files here https://github.com/e-newton/VectorFieldScreensaver/tree/master/src/com/company

as well I believe the builds found here https://github.com/e-newton/VectorFieldScreensaver/tree/master/out/artifacts/VectorField

I am unsure if it still works, I made this a while ago while I was very inexperienced and no longer have java development environment set up. There were some issues with how the event handlers were working when the screensaver was running and some performance issues. My recommendation would be to copy/paste the source files into your own repository, build from there, and make improvements as you see fit 😃

**Comment by xGhostRider-Tommy** [comment]
> Hi @xGhostRider-Tommy you can find the source files here https://github.com/e-newton/VectorFieldScreensaver/tree/master/src/com/company
> 
> as well I believe the builds found here https://github.com/e-newton/VectorFieldScreensaver/tree/master/out/artifacts/VectorField
> 
> I am unsure if it still works, I made this a while ago while I was very inexperienced and no longer have java development environment set up. There were some issues with how the event handlers were working when the screensaver was running and some performance issues. My recommendation would be to copy/paste the source files into your own repository, build from there, and make improvements as you see fit 😃

thanks!😃
